name: Deploy website on S3

on:
  push:
    branches:
      - master
  
jobs:
  deoloy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Deploy
        run: aws s3 sync ./build s3://${{ secrests.AWS_BUCKET_NAME }}/food